### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ivangretsky** [ocReaper/redmine-desktop#27]
Good day!
This is a project I would love to build myself (if I knew how). Looks very useful for Redmine users. But is it alive? No code commits for a year... Are there any plans to continue development?

**Comment by ocReaper** [comment]
Hi @ivangretsky ,

I had no time to continue the project, also had no motivation.
But now that someone could get a good use of it, I think I continue it.
Also I'm planning to migrate my personal time tracker into the project.

**Comment by ivangretsky** [comment]
I think if you make it right it will be useful to many. If you feel confident, maybe even crowdfund it on  kickstarter, indiegogo or patreon.
